# Default values for kube-ts-server
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: kubejs/kube-ts-server
  tag: 1.1.3
  pullPolicy: IfNotPresent
  containerPort: 3000

livenessProbe:
  httpGet:
    path: /health/liveness
    port: 3000
  initialDelaySeconds: 60
  periodSeconds: 5

readinessProbe:
  httpGet:
    path: /health/readiness
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 5

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nameOverride: ''
fullnameOverride: ''

certmanager:
  email: mariuszrajczakowski@gmail.com

cluster_issuer:
  server: https://acme-v02.api.letsencrypt.org/directory

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
    certmanager.k8s.io/cluster-issuer: kube-ts-server
  paths: 
    - backend:
      serviceName: kube-ts-server
      servicePort: 80
  hosts:
    - api.mariuszrajczakowski.me
  tls:
    - hosts:
      - api.mariuszrajczakowski.me

nodeSelector: {}

tolerations: []

affinity: {}
# Configmap: adjust the values below
knex_database: kube-ts-server
knex_client: mysql
knex_host: localhost

# Secret: adjust the values below
knex_user: root
knex_password: password
jwt_secret: secret
smtp_user: smtp_user
smtp_pass: smtp_pass
