replicaCount: 1
revisionHistoryLimit: 1

image:
  repository: kubejs/kube-ts-server
  tag: 1.1.1
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 300m
      memory: 450Mi
livenessProbe:
  httpGet:
    path: /health/liveness
    port: 3000
  initialDelaySeconds: 60
  periodSeconds: 5
readinessProbe:
  httpGet:
    path: /health/readiness
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 5

ingress: 
  apiHost: api.mariuszrajczakowski.me
  # clientHost: client.mariuszrajczakowski.me

service:
  name: Node
  # type: NodePort
  servicePort: 80
  serviceTargetPort: 3000
