apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-ts-server.fullname" . }}
labels:
  app.kubernetes.io/name: {{ include "kube-ts-server.name" . }}
  app.kubernetes.io/instance: {{ .Release.Name }}
  app.kubernetes.io/managed-by: {{ .Release.Service }}
  helm.sh/chart: {{ include "kube-ts-server.chart" . }}
data:
{{- range $key, $value := .Values.configMap }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
