apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-ts-server
spec:
  selector:
    matchLabels:
      app: kube-ts-server
  replicas: 2
  template:
    metadata:
      labels:
        app: kube-ts-server
    spec:
      containers:
      - name: kube-ts-server
        image: kubejs/kube-ts-server
        ports:
        - containerPort: 3000
        env:
        - name: KNEX_DATABASE
          valueFrom:
            configMapKeyRef:
              name: kube-ts-configmap
              key: knex_database
        - name: KNEX_CLIENT
          valueFrom:
            configMapKeyRef:
              name: kube-ts-configmap
              key: knex_client
        - name: KNEX_HOST
          valueFrom:
            configMapKeyRef:
              name: kube-ts-configmap
              key: knex_host
        - name: KNEX_USER
          valueFrom:
            secretKeyRef:
              name: kube-ts-secret
              key: knex_user
        - name: KNEX_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kube-ts-secret
              key: knex_password         
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
