# source https://stackoverflow.com/questions/43189487/create-kubernetes-nginx-ingress-without-gcp-load-balancer
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: my-ingress
# spec:
#   rules:
#     - host: api.example.com # change to custom domain
#       http:
#         paths:
#           - path: /
#             backend:
#               serviceName: my-app-service # obviously point this to a valid service + port
#               servicePort: 80

# TODO: remove comments and use .Values instead of hardcoded vars
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kube-ts-ingress
  annotations:  
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - api.mariuszrajczakowski.me
    secretName: letsencrypt-prod
  rules:
  - host: api.mariuszrajczakowski.me
    http:
      paths:
      - backend:
        serviceName: kube-ts-server
        servicePort: 80
