apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-ts-server.name" . }}
type: Opaque
data:
  knex_user: {{ .Values.knex_user | b64enc | quote }}
  knex_password: {{ .Values.knex_password | b64enc | quote }}
  jwt_secret: {{ .Values.jwt_secret | b64enc | quote }}
  smtp_user: {{ .Values.smtp_user | b64enc | quote }}
  smtp_pass: {{ .Values.smtp_pass | b64enc | quote }}
