apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-ts-server.fullname" . }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret }}
    {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
